import { extractJsonObject } from "../shared/json";
import { arrayBufferToBase64 } from "../shared/base64";
import type { Env,VisionResult } from "../types";
function normalize(raw:unknown,provider:string):VisionResult{
  const envelope=raw as{result?:unknown},output=(envelope?.result&&typeof envelope.result==="object"?envelope.result:raw) as{answer?:unknown;caption?:unknown;response?:unknown};
  const text=typeof raw==="string"?raw:typeof output.answer==="string"?output.answer:typeof output.caption==="string"?output.caption:typeof output.response==="string"?output.response:JSON.stringify(raw),obj=extractJsonObject(text)||{};
  const kind=["CLOCK","RECEIPT","BANK_SLIP","ONLINE_ORDER","UNKNOWN"].includes(String(obj.kind))?String(obj.kind) as VisionResult["kind"]:"UNKNOWN";
  const num=(v:unknown):number|null=>v==null||v===""?null:Number.isFinite(Number(v))?Number(v):null;
  return{kind,hour:num(obj.hour),minute:num(obj.minute),month:num(obj.month),day:num(obj.day),weekday:obj.weekday?String(obj.weekday):null,confidence:Number(obj.confidence||0),clockFullyVisible:typeof obj.clockFullyVisible==="boolean"?obj.clockFullyVisible:null,clockPresent:typeof obj.clockPresent==="boolean"?obj.clockPresent:null,clockConfidence:Number(obj.clockConfidence||0),overlayPresent:Boolean(obj.overlayPresent),overlayTextWhite:Boolean(obj.overlayTextWhite),photoDate:obj.photoDate?String(obj.photoDate):null,photoTime:obj.photoTime?String(obj.photoTime):null,latitude:num(obj.latitude),longitude:num(obj.longitude),locationText:String(obj.locationText||""),overlayRawText:String(obj.overlayRawText||""),overlayConfidence:Number(obj.overlayConfidence||0),needsNewPhoto:Boolean(obj.needsNewPhoto),note:String(obj.note||""),provider,raw};
}
export async function readImageWithWorkersAI(env:Env,image:ArrayBuffer):Promise<VisionResult>{
  const prompt=`Return JSON only. Classify as CLOCK, RECEIPT, BANK_SLIP, ONLINE_ORDER, or UNKNOWN. For a CLOCK attendance photo inspect the whole image and every corner. The only authoritative attendance source is a camera overlay printed in white text containing date, time, numeric latitude/longitude, and a human-readable address or place name. The overlay may be anywhere. Copy only the visible place name into locationText and never geocode it. The wide black MaliPang wall clock with white LED digits, Mon-Sun list and green side digits is shop-presence evidence only; never use its digits as attendance time/date. Normalize overlay date to Gregorian YYYY-MM-DD and time to 24-hour HH:mm:ss. Never infer from current time, LINE time, metadata, or clock digits. Schema: {"kind":"CLOCK|RECEIPT|BANK_SLIP|ONLINE_ORDER|UNKNOWN","hour":null,"minute":null,"month":null,"day":null,"weekday":null,"confidence":0..1,"clockFullyVisible":boolean|null,"clockPresent":boolean|null,"clockConfidence":0..1,"overlayPresent":boolean,"overlayTextWhite":boolean,"photoDate":string|null,"photoTime":string|null,"latitude":number|null,"longitude":number|null,"locationText":string,"overlayRawText":string,"overlayConfidence":0..1,"needsNewPhoto":boolean,"note":""}. Use null/false and needsNewPhoto=true when required overlay or clock evidence is unclear.`;
  const input={task:"query",image:`data:image/jpeg;base64,${arrayBufferToBase64(image)}`,question:prompt,reasoning:false,temperature:0,max_tokens:350,stream:false};
  return normalize(await env.AI.run(env.WORKERS_AI_MODEL,input),"workers-ai");
}
