import { enqueueSheetSync } from "../db/repositories";
import { calculatePayroll,LATE_GRACE_MIN } from "../domain/payroll";
import { isoDateInBangkok,weekStartMonday } from "../shared/time";
import type { Env } from "../types";
import { getEmployeeById,refreshWeeklyPayroll,resolveWageSnapshot } from "./repository";
import { recalculateDailyPayroll } from "./recalculate";

interface DailyRow{employee_id:string;work_date:string}
interface ShiftRow{employee_id:string;work_date:string;scheduled_in:string;scheduled_out:string;daily_wage_snapshot_satang:number;wage_source_id:string;version:number}
export async function finalizeMissingPunchPayrolls(env:Env):Promise<{onePunch:number;noPunch:number}>{
  const today=isoDateInBangkok(),one=await env.DB.prepare(`SELECT employee_id,work_date FROM attendance_daily WHERE work_date<? AND finalized_at IS NULL AND review_flag=0 AND ((time_in IS NULL AND time_out IS NOT NULL) OR (time_in IS NOT NULL AND time_out IS NULL)) ORDER BY work_date,employee_id LIMIT 100`).bind(today).all<DailyRow>();
  let onePunch=0;for(const row of one.results||[]){await recalculateDailyPayroll(env,String(row.employee_id),String(row.work_date),{finalizeMissingPunch:true,traceId:`missing_punch_${row.employee_id}_${row.work_date}`});onePunch++;}
  const missing=await env.DB.prepare(`SELECT s.employee_id,s.work_date,s.scheduled_in,s.scheduled_out,s.daily_wage_snapshot_satang,s.wage_source_id,s.version FROM employee_shift_days s LEFT JOIN attendance_daily d ON d.employee_id=s.employee_id AND d.work_date=s.work_date WHERE s.status='EXPECTED' AND s.work_date<? AND d.employee_id IS NULL ORDER BY s.work_date,s.employee_id LIMIT 100`).bind(today).all<ShiftRow>();
  let noPunch=0;for(const shift of missing.results||[]){const employee=await getEmployeeById(env,String(shift.employee_id));if(!employee)continue;const wage=await resolveWageSnapshot(env,employee,String(shift.work_date)),payroll=calculatePayroll({employee:{...employee,scheduledIn:String(shift.scheduled_in),scheduledOut:String(shift.scheduled_out),dailyWageSatang:wage.dailyWageSatang},timeIn:null,timeOut:null,review:true,finalizeMissingPunch:true}),now=new Date().toISOString(),version=1,shiftVersion=Number(shift.version||0)+1;
    await env.DB.batch([
      env.DB.prepare(`UPDATE employee_shift_days SET daily_wage_snapshot_satang=?,wage_source_id=?,version=version+1,updated_at=? WHERE employee_id=? AND work_date=?`).bind(wage.dailyWageSatang,wage.wageSourceId,now,shift.employee_id,shift.work_date),
      env.DB.prepare(`INSERT OR IGNORE INTO attendance_daily(employee_id,work_date,scheduled_in,scheduled_out,grace_min,late_deduction_satang,early_deduction_satang,time_in,time_out,work_minutes,late_minutes,early_out_minutes,daily_wage_satang,confirmed_wage_satang,pending_wage_satang,pay_status,review_flag,version,updated_at,wage_source_id,daily_wage_snapshot_satang,late_deduction_applied_satang,missing_punch_type,missing_punch_deduction_satang,ot_approved_satang,other_adjustment_satang,net_pay_satang,payroll_policy_code,finalized_at) VALUES(?,?,?,?,?,?,?,NULL,NULL,?,?,?,?,?,?,?,1,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(shift.employee_id,shift.work_date,shift.scheduled_in,shift.scheduled_out,LATE_GRACE_MIN,employee.lateDeductionSatang,employee.earlyDeductionSatang,payroll.workMinutes,payroll.lateMinutes,payroll.earlyOutMinutes,wage.dailyWageSatang,payroll.confirmedWageSatang,payroll.pendingWageSatang,payroll.payStatus,version,now,wage.wageSourceId,wage.dailyWageSatang,payroll.lateDeductionSatang,payroll.missingPunchType,payroll.missingPunchDeductionSatang,payroll.otApprovedSatang,payroll.otherAdjustmentSatang,payroll.netPaySatang,payroll.policyCode,now)
    ]);
    const weeklyVersion=await refreshWeeklyPayroll(env,String(shift.employee_id),String(shift.work_date),version,now),traceId=`absence_${shift.employee_id}_${shift.work_date}`;await enqueueSheetSync(env,{kind:"SHEETS_SYNC",entityType:"SHIFT_SCHEDULE",entityKey:`${shift.employee_id}|${shift.work_date}`,entityVersion:shiftVersion,traceId});await enqueueSheetSync(env,{kind:"SHEETS_SYNC",entityType:"DAILY_PAYROLL",entityKey:`${shift.employee_id}|${shift.work_date}`,entityVersion:version,traceId});await enqueueSheetSync(env,{kind:"SHEETS_SYNC",entityType:"WEEKLY_PAYROLL",entityKey:`${shift.employee_id}|${weekStartMonday(String(shift.work_date))}`,entityVersion:weeklyVersion,traceId});noPunch++;}
  return{onePunch,noPunch};
}
