import { createFixedOtRequest,finalizeFixedOt } from "../admin/payroll-admin";
import { pushText } from "../line/api";
import { addDays,isIsoDate,isoDateInBangkok,minutesOf } from "../shared/time";
import type { Env,LineEvent } from "../types";

export type OwnerOtCommand=
  |{kind:"CREATE";employeeRef:string;workDate:string;fixedAmountBaht:number;plannedStart:string|null;plannedEnd:string|null;reason:string}
  |{kind:"APPROVE";otId:string;finalAmountBaht:number|null;note:string}
  |{kind:"REJECT";otId:string;note:string};

function dateToken(value:string,today=isoDateInBangkok()):string|null{const v=value.trim().toLowerCase();if(v==="today"||v==="วันนี้")return today;if(v==="tomorrow"||v==="พรุ่งนี้")return addDays(today,1);return isIsoDate(value)?value:null;}
function timeRange(value:string):{start:string;end:string}|null{const match=/^(\d{1,2}:\d{2})-(\d{1,2}:\d{2})$/.exec(value);if(!match)return null;const start=match[1]!,end=match[2]!;try{minutesOf(start);minutesOf(end);if(minutesOf(end)<=minutesOf(start))return null;}catch{return null;}return{start,end};}
export function parseOwnerOtCommand(text:string,today=isoDateInBangkok()):OwnerOtCommand|null{
  const trimmed=text.trim(),prefix=/^(OT|โอที)\s+/i.exec(trimmed);if(!prefix)return null;const rest=trimmed.slice(prefix[0].length).trim(),parts=rest.split(/\s+/).filter(Boolean);if(!parts.length)throw new Error("OT command is incomplete");
  const action=parts[0]!.toLowerCase();if(["approve","อนุมัติ"].includes(action)){const otId=parts[1]||"",amount=parts[2]&&/^\d+(?:\.\d{1,2})?$/.test(parts[2])?Number(parts[2]):null,note=parts.slice(amount==null?2:3).join(" ");if(!otId)throw new Error("OT ID is required");return{kind:"APPROVE",otId,finalAmountBaht:amount,note};}
  if(["reject","ไม่อนุมัติ","ปฏิเสธ"].includes(action)){const otId=parts[1]||"",note=parts.slice(2).join(" ");if(!otId)throw new Error("OT ID is required");return{kind:"REJECT",otId,note};}
  const dateIndex=parts.findIndex(value=>dateToken(value,today)!==null);if(dateIndex<1)throw new Error("Employee and work date are required");const employeeRef=parts.slice(0,dateIndex).join(" "),workDate=dateToken(parts[dateIndex]!,today)!,amount=Number(parts[dateIndex+1]);if(!Number.isFinite(amount)||amount<=0)throw new Error("Fixed OT amount is required");let cursor=dateIndex+2,plannedStart:string|null=null,plannedEnd:string|null=null;const timeToken=parts[cursor]||"",looksLikeRange=/^\d{1,2}:\d{2}-\d{1,2}:\d{2}$/.test(timeToken),range=timeToken?timeRange(timeToken):null;if(looksLikeRange&&!range)throw new Error("OT time range is invalid");if(range){plannedStart=range.start;plannedEnd=range.end;cursor++;}const reason=parts.slice(cursor).join(" ").trim();if(reason.length<3)throw new Error("OT reason is required");return{kind:"CREATE",employeeRef,workDate,fixedAmountBaht:amount,plannedStart,plannedEnd,reason};
}

async function resolveEmployeeId(env:Env,reference:string):Promise<string>{const row=await env.DB.prepare(`SELECT employee_id FROM employees WHERE employee_id=? OR LOWER(staff_name)=LOWER(?) LIMIT 1`).bind(reference,reference).first<{employee_id:string}>();if(!row)throw new Error(`Employee not found: ${reference}`);return String(row.employee_id);}
function help(error?:unknown):string{return[`คำสั่ง OT ไม่ถูกต้อง${error?`\nสาเหตุ: ${String(error instanceof Error?error.message:error)}`:""}`,"","สร้าง OT:","OT Win วันนี้ 200 16:00-18:00 เตรียมไส้เพิ่ม","OT EMP001 2026-08-01 100 ช่วยปิดร้าน","","ยืนยันหลังทำงาน:","OT อนุมัติ <OT_ID> 200","OT ไม่อนุมัติ <OT_ID> เหตุผล"].join("\n");}
export async function handleOwnerPayrollText(env:Env,event:LineEvent):Promise<boolean>{
  const text=event.message?.text||"",to=event.source.userId||"",traceId=`owner_ot_${event.message?.id||crypto.randomUUID()}`;if(!/^(OT|โอที)(\s|$)/i.test(text.trim()))return false;if(to!==env.LINE_OWNER_USER_ID){await pushText(env,to,"คำสั่ง OT ใช้ได้เฉพาะบัญชี Owner เท่านั้น",traceId);return true;}
  try{const command=parseOwnerOtCommand(text);if(!command)return false;if(command.kind==="CREATE"){const employeeId=await resolveEmployeeId(env,command.employeeRef),result=await createFixedOtRequest(env,{employeeId,workDate:command.workDate,reason:command.reason,plannedStart:command.plannedStart,plannedEnd:command.plannedEnd,fixedAmountBaht:command.fixedAmountBaht,note:"Created from Owner LINE"});await pushText(env,to,`สร้าง OT เรียบร้อย ✅\nOT ID: ${result.otId}\nพนักงาน: ${command.employeeRef}\nวันที่: ${command.workDate}\nยอดเหมา: ${command.fixedAmountBaht} บาท\nส่งให้พนักงานยืนยันแล้ว`,traceId);return true;}if(command.kind==="APPROVE"){const result=await finalizeFixedOt(env,{otId:command.otId,approved:true,...(command.finalAmountBaht==null?{}:{finalAmountBaht:command.finalAmountBaht}),note:command.note});await pushText(env,to,`อัปเดต OT เรียบร้อย ✅\nOT ID: ${result.otId}\nสถานะ: ${result.status}`,traceId);return true;}const result=await finalizeFixedOt(env,{otId:command.otId,approved:false,note:command.note});await pushText(env,to,`อัปเดต OT เรียบร้อย ✅\nOT ID: ${result.otId}\nสถานะ: ${result.status}`,traceId);return true;}catch(error){await pushText(env,to,help(error),traceId);return true;}
}
