import { enqueueSheetSync } from "../db/repositories";
import { calculatePayroll,LATE_GRACE_MIN } from "../domain/payroll";
import { approvedOtSatangForDay,getEmployeeById,resolveWageSnapshot,weeklyPayrollStatement } from "../payroll/repository";
import { randomId } from "../shared/ids";
import { weekStartMonday } from "../shared/time";
import type { Env } from "../types";
import { validateCorrection } from "./correction-validation";
export async function correctAttendance(env:Env,rawInput:unknown):Promise<{eventId:string;version:number}>{
  const input=validateCorrection(rawInput),employee=await getEmployeeById(env,input.employeeId);if(!employee)throw new Error("Employee not found");
  const before=await env.DB.prepare(`SELECT * FROM attendance_daily WHERE employee_id=? AND work_date=?`).bind(input.employeeId,input.workDate).first<Record<string,unknown>>(),version=Number(before?.version||0)+1;
  const previousWage=Number(before?.daily_wage_snapshot_satang||before?.daily_wage_satang||0),resolved=previousWage>0?{wageSourceId:String(before?.wage_source_id||"LEGACY_SNAPSHOT"),dailyWageSatang:previousWage}:await resolveWageSnapshot(env,employee,input.workDate),otApprovedSatang=await approvedOtSatangForDay(env,input.employeeId,input.workDate);
  const payroll=calculatePayroll({employee:{...employee,dailyWageSatang:resolved.dailyWageSatang},timeIn:input.timeIn,timeOut:input.timeOut,review:false,finalizeMissingPunch:true,otApprovedSatang}),eventId=randomId("admin_att"),messageId=randomId("admin_msg"),now=new Date().toISOString(),weekStart=weekStartMonday(input.workDate);
  await env.DB.batch([
    env.DB.prepare(`INSERT INTO attendance_events(event_id,webhook_event_id,message_id,employee_id,work_date,punch_type,official_time,status,confidence,line_time,line_diff_minutes,image_key,note,validation_code,trace_id,created_at,version) VALUES(?,?,?,?,?,'REVIEW',?,'NORMAL',1,'',0,'',?,'ADMIN_CORRECTION',?,?,?)`).bind(eventId,messageId,messageId,input.employeeId,input.workDate,input.timeOut,input.reason.trim(),eventId,now,version),
    env.DB.prepare(`INSERT INTO attendance_daily(
      employee_id,work_date,scheduled_in,scheduled_out,grace_min,late_deduction_satang,early_deduction_satang,time_in,time_out,work_minutes,late_minutes,early_out_minutes,daily_wage_satang,confirmed_wage_satang,pending_wage_satang,pay_status,review_flag,version,updated_at,
      wage_source_id,daily_wage_snapshot_satang,late_deduction_applied_satang,missing_punch_type,missing_punch_deduction_satang,ot_approved_satang,other_adjustment_satang,net_pay_satang,payroll_policy_code,finalized_at
    ) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,0,?,?,?,?,?,?,?,?,?,?,?,?)
    ON CONFLICT(employee_id,work_date) DO UPDATE SET time_in=excluded.time_in,time_out=excluded.time_out,work_minutes=excluded.work_minutes,late_minutes=excluded.late_minutes,early_out_minutes=excluded.early_out_minutes,confirmed_wage_satang=excluded.confirmed_wage_satang,pending_wage_satang=excluded.pending_wage_satang,pay_status=excluded.pay_status,review_flag=0,version=excluded.version,updated_at=excluded.updated_at,wage_source_id=excluded.wage_source_id,daily_wage_snapshot_satang=excluded.daily_wage_snapshot_satang,late_deduction_applied_satang=excluded.late_deduction_applied_satang,missing_punch_type=excluded.missing_punch_type,missing_punch_deduction_satang=excluded.missing_punch_deduction_satang,ot_approved_satang=excluded.ot_approved_satang,other_adjustment_satang=excluded.other_adjustment_satang,net_pay_satang=excluded.net_pay_satang,payroll_policy_code=excluded.payroll_policy_code,finalized_at=excluded.finalized_at`).bind(input.employeeId,input.workDate,employee.scheduledIn,employee.scheduledOut,LATE_GRACE_MIN,employee.lateDeductionSatang,employee.earlyDeductionSatang,input.timeIn,input.timeOut,payroll.workMinutes,payroll.lateMinutes,payroll.earlyOutMinutes,resolved.dailyWageSatang,payroll.confirmedWageSatang,payroll.pendingWageSatang,payroll.payStatus,version,now,resolved.wageSourceId,resolved.dailyWageSatang,payroll.lateDeductionSatang,payroll.missingPunchType,payroll.missingPunchDeductionSatang,payroll.otApprovedSatang,payroll.otherAdjustmentSatang,payroll.netPaySatang,payroll.policyCode,now),
    weeklyPayrollStatement(env,input.employeeId,input.workDate,version,now),
    env.DB.prepare(`INSERT INTO admin_audit(id,action,entity_key,reason,before_json,after_json,created_at) VALUES(?,?,?,?,?,?,?)`).bind(crypto.randomUUID(),"ATTENDANCE_CORRECTION",`${input.employeeId}|${input.workDate}`,input.reason.trim(),JSON.stringify(before),JSON.stringify({timeIn:input.timeIn,timeOut:input.timeOut,wageSourceId:resolved.wageSourceId,payroll}),now)
  ]);
  const stub=env.ATTENDANCE_COORDINATOR.get(env.ATTENDANCE_COORDINATOR.idFromName(`${input.employeeId}|${input.workDate}`));await stub.fetch("https://attendance.local/sync",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({timeIn:input.timeIn,timeOut:input.timeOut,review:false,version})});
  for(const job of [{entityType:"ATTENDANCE_EVENT" as const,entityKey:eventId},{entityType:"DAILY_PAYROLL" as const,entityKey:`${input.employeeId}|${input.workDate}`},{entityType:"WEEKLY_PAYROLL" as const,entityKey:`${input.employeeId}|${weekStart}`}])await enqueueSheetSync(env,{kind:"SHEETS_SYNC",...job,entityVersion:version,traceId:eventId});
  return{eventId,version};
}
