import { enqueueSheetSync } from "../db/repositories";
import { calculatePayroll } from "../domain/payroll";
import { randomId } from "../shared/ids";
import { addDays,weekStartMonday } from "../shared/time";
import type { Employee,Env } from "../types";
import { validateCorrection } from "./correction-validation";
export async function correctAttendance(env:Env,rawInput:unknown):Promise<{eventId:string;version:number}>{
  const input=validateCorrection(rawInput);
  const row=await env.DB.prepare(`SELECT * FROM employees WHERE employee_id=?`).bind(input.employeeId).first<Record<string,unknown>>();if(!row)throw new Error("Employee not found");
  const employee:Employee={employeeId:String(row.employee_id),staffName:String(row.staff_name),lineUserId:String(row.line_user_id),scheduledIn:String(row.scheduled_in),scheduledOut:String(row.scheduled_out),dailyWageSatang:Number(row.daily_wage_satang),graceMin:Number(row.grace_min),lateDeductionSatang:Number(row.late_deduction_satang),earlyDeductionSatang:Number(row.early_deduction_satang),canSubmitExpense:Number(row.can_submit_expense)===1,status:String(row.status)==="ACTIVE"?"ACTIVE":"INACTIVE"};
  const before=await env.DB.prepare(`SELECT * FROM attendance_daily WHERE employee_id=? AND work_date=?`).bind(input.employeeId,input.workDate).first<Record<string,unknown>>(),version=Number(before?.version||0)+1,payroll=calculatePayroll({employee,timeIn:input.timeIn,timeOut:input.timeOut,review:false}),eventId=randomId("admin_att"),messageId=randomId("admin_msg"),now=new Date().toISOString(),weekStart=weekStartMonday(input.workDate),paySunday=addDays(weekStart,6);
  await env.DB.batch([
    env.DB.prepare(`INSERT INTO attendance_events(event_id,webhook_event_id,message_id,employee_id,work_date,punch_type,official_time,status,confidence,line_time,line_diff_minutes,image_key,note,validation_code,trace_id,created_at,version) VALUES(?,?,?,?,?,'REVIEW',?,'NORMAL',1,'',0,'',?,'ADMIN_CORRECTION',?,?,?)`).bind(eventId,messageId,messageId,input.employeeId,input.workDate,input.timeOut,input.reason.trim(),eventId,now,version),
    env.DB.prepare(`INSERT INTO attendance_daily(employee_id,work_date,scheduled_in,scheduled_out,grace_min,late_deduction_satang,early_deduction_satang,time_in,time_out,work_minutes,late_minutes,early_out_minutes,daily_wage_satang,confirmed_wage_satang,pending_wage_satang,pay_status,review_flag,version,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,0,?,?) ON CONFLICT(employee_id,work_date) DO UPDATE SET time_in=excluded.time_in,time_out=excluded.time_out,work_minutes=excluded.work_minutes,late_minutes=excluded.late_minutes,early_out_minutes=excluded.early_out_minutes,confirmed_wage_satang=excluded.confirmed_wage_satang,pending_wage_satang=excluded.pending_wage_satang,pay_status=excluded.pay_status,review_flag=0,version=excluded.version,updated_at=excluded.updated_at`).bind(input.employeeId,input.workDate,employee.scheduledIn,employee.scheduledOut,employee.graceMin,employee.lateDeductionSatang,employee.earlyDeductionSatang,input.timeIn,input.timeOut,payroll.workMinutes,payroll.lateMinutes,payroll.earlyOutMinutes,employee.dailyWageSatang,payroll.confirmedWageSatang,payroll.pendingWageSatang,payroll.payStatus,version,now),
    env.DB.prepare(`INSERT INTO payroll_weekly(employee_id,week_start,pay_sunday,work_days,confirmed_amount_satang,pending_amount_satang,status,version,updated_at) SELECT ?,?,?,COALESCE(SUM(CASE WHEN time_in IS NOT NULL AND time_out IS NOT NULL THEN 1 ELSE 0 END),0),COALESCE(SUM(confirmed_wage_satang),0),COALESCE(SUM(pending_wage_satang),0),CASE WHEN COALESCE(SUM(pending_wage_satang),0)>0 THEN 'REVIEW' WHEN COALESCE(SUM(confirmed_wage_satang),0)>0 THEN 'READY' ELSE 'NO_AMOUNT' END,?,? FROM attendance_daily WHERE employee_id=? AND work_date BETWEEN ? AND ? ON CONFLICT(employee_id,week_start) DO UPDATE SET work_days=excluded.work_days,confirmed_amount_satang=excluded.confirmed_amount_satang,pending_amount_satang=excluded.pending_amount_satang,status=excluded.status,version=payroll_weekly.version+1,updated_at=excluded.updated_at`).bind(input.employeeId,weekStart,paySunday,version,now,input.employeeId,weekStart,paySunday),
    env.DB.prepare(`INSERT INTO admin_audit(id,action,entity_key,reason,before_json,after_json,created_at) VALUES(?,?,?,?,?,?,?)`).bind(crypto.randomUUID(),"ATTENDANCE_CORRECTION",`${input.employeeId}|${input.workDate}`,input.reason.trim(),JSON.stringify(before),JSON.stringify({timeIn:input.timeIn,timeOut:input.timeOut,payroll}),now)
  ]);
  const stub=env.ATTENDANCE_COORDINATOR.get(env.ATTENDANCE_COORDINATOR.idFromName(`${input.employeeId}|${input.workDate}`));await stub.fetch("https://attendance.local/sync",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({timeIn:input.timeIn,timeOut:input.timeOut,review:false,version})});
  for(const job of [{entityType:"ATTENDANCE_EVENT" as const,entityKey:eventId},{entityType:"DAILY_PAYROLL" as const,entityKey:`${input.employeeId}|${input.workDate}`},{entityType:"WEEKLY_PAYROLL" as const,entityKey:`${input.employeeId}|${weekStart}`}])await enqueueSheetSync(env,{kind:"SHEETS_SYNC",...job,entityVersion:version,traceId:eventId});
  return{eventId,version};
}
