import { enqueueSheetSync } from "../db/repositories";
import { actualOtMinutes,fixedOtSatang } from "../domain/ot";
import { pushConfirmation,pushText } from "../line/api";
import { getEmployeeById } from "../payroll/repository";
import { recalculateDailyPayroll } from "../payroll/recalculate";
import { addDays,isIsoDate,isoDateInBangkok,minutesOf } from "../shared/time";
import type { Env,FixedOtRequestInput } from "../types";

function optionalTime(value:unknown,name:string):string|null{const text=String(value??"").trim();if(!text)return null;try{minutesOf(text);}catch{throw new Error(`${name} must be HH:mm`);}return text;}
export async function setEmployeeWage(env:Env,raw:unknown):Promise<{wageId:string;version:number}>{
  if(!raw||typeof raw!=="object")throw new Error("Invalid wage payload");const body=raw as Record<string,unknown>,employeeId=String(body.employeeId||"").trim(),effectiveFrom=String(body.effectiveFrom||"").trim(),amountBaht=Number(body.dailyWageBaht),note=String(body.note||"").trim();if(!/^[A-Za-z0-9_-]{1,40}$/.test(employeeId)||!isIsoDate(effectiveFrom)||!Number.isFinite(amountBaht)||amountBaht<0)throw new Error("employeeId, dailyWageBaht and effectiveFrom are required");
  const employee=await getEmployeeById(env,employeeId);if(!employee)throw new Error("Employee not found");const amountSatang=Math.round(amountBaht*100),wageId=`wage_${employeeId}_${effectiveFrom.replaceAll("-","")}`,now=new Date().toISOString(),today=isoDateInBangkok(),existing=await env.DB.prepare(`SELECT * FROM employee_wage_history WHERE employee_id=? AND effective_from=?`).bind(employeeId,effectiveFrom).first<Record<string,unknown>>(),previous=await env.DB.prepare(`SELECT wage_id,version FROM employee_wage_history WHERE employee_id=? AND effective_from<? AND (effective_to IS NULL OR effective_to>=?) ORDER BY effective_from DESC LIMIT 1`).bind(employeeId,effectiveFrom,effectiveFrom).first<{wage_id:string;version:number}>(),next=await env.DB.prepare(`SELECT effective_from FROM employee_wage_history WHERE employee_id=? AND effective_from>? ORDER BY effective_from LIMIT 1`).bind(employeeId,effectiveFrom).first<{effective_from:string}>(),effectiveTo=next?.effective_from?addDays(next.effective_from,-1):null,version=Number(existing?.version||0)+1;
  const statements=[
    env.DB.prepare(`UPDATE employee_wage_history SET effective_to=?,updated_at=?,version=version+1 WHERE employee_id=? AND effective_from<? AND (effective_to IS NULL OR effective_to>=?)`).bind(addDays(effectiveFrom,-1),now,employeeId,effectiveFrom,effectiveFrom),
    env.DB.prepare(`INSERT INTO employee_wage_history(wage_id,employee_id,daily_wage_satang,effective_from,effective_to,source,note,version,created_at,updated_at) VALUES(?,?,?,?,?,'OWNER_ADMIN',?,?,?,?) ON CONFLICT(employee_id,effective_from) DO UPDATE SET daily_wage_satang=excluded.daily_wage_satang,effective_to=excluded.effective_to,source=excluded.source,note=excluded.note,version=employee_wage_history.version+1,updated_at=excluded.updated_at`).bind(wageId,employeeId,amountSatang,effectiveFrom,effectiveTo,note,version,now,now),
    env.DB.prepare(`UPDATE employees SET daily_wage_satang=COALESCE((SELECT daily_wage_satang FROM employee_wage_history WHERE employee_id=? AND effective_from<=? AND (effective_to IS NULL OR effective_to>=?) ORDER BY effective_from DESC LIMIT 1),daily_wage_satang),updated_at=? WHERE employee_id=?`).bind(employeeId,today,today,now,employeeId),
    env.DB.prepare(`INSERT INTO admin_audit(id,action,entity_key,reason,before_json,after_json,created_at) VALUES(?,?,?,?,?,?,?)`).bind(crypto.randomUUID(),"WAGE_CHANGE",wageId,note||"Owner wage update",JSON.stringify(existing),JSON.stringify({employeeId,dailyWageBaht:amountBaht,effectiveFrom,effectiveTo}),now)
  ];await env.DB.batch(statements);const traceId=`wage_${crypto.randomUUID()}`;await enqueueSheetSync(env,{kind:"SHEETS_SYNC",entityType:"WAGE_HISTORY",entityKey:wageId,entityVersion:version,traceId});if(previous)await enqueueSheetSync(env,{kind:"SHEETS_SYNC",entityType:"WAGE_HISTORY",entityKey:String(previous.wage_id),entityVersion:Number(previous.version||0)+1,traceId});return{wageId,version};
}

export async function createFixedOtRequest(env:Env,raw:unknown):Promise<{otId:string;version:number}>{
  if(!raw||typeof raw!=="object")throw new Error("Invalid OT payload");const body=raw as Record<string,unknown>,input:FixedOtRequestInput={employeeId:String(body.employeeId||"").trim(),workDate:String(body.workDate||"").trim(),reason:String(body.reason||"").trim(),fixedAmountBaht:Number(body.fixedAmountBaht),...(body.plannedStart==null?{}:{plannedStart:optionalTime(body.plannedStart,"plannedStart")}),...(body.plannedEnd==null?{}:{plannedEnd:optionalTime(body.plannedEnd,"plannedEnd")}),...(body.note==null?{}:{note:String(body.note).trim()})};if(!/^[A-Za-z0-9_-]{1,40}$/.test(input.employeeId)||!isIsoDate(input.workDate)||input.reason.length<3)throw new Error("employeeId, workDate and reason are required");const amountSatang=fixedOtSatang(input.fixedAmountBaht),employee=await getEmployeeById(env,input.employeeId);if(!employee)throw new Error("Employee not found");const plannedStart=input.plannedStart??null,plannedEnd=input.plannedEnd??null;if(plannedStart&&plannedEnd&&minutesOf(plannedEnd)<=minutesOf(plannedStart))throw new Error("plannedEnd must be later than plannedStart");const otId=`ot_${crypto.randomUUID()}`,now=new Date().toISOString(),version=1,note=input.note||"";
  await env.DB.batch([env.DB.prepare(`INSERT INTO ot_requests(ot_id,employee_id,work_date,reason,planned_start,planned_end,fixed_amount_satang,requested_by,owner_preapproved_at,employee_confirm_status,owner_final_status,owner_final_amount_satang,actual_ot_minutes,status,note,version,created_at,updated_at) VALUES(?,?,?,?,?,?,?,'OWNER_ADMIN',?,'PENDING','PENDING',0,0,'PENDING_EMPLOYEE',?,1,?,?)`).bind(otId,input.employeeId,input.workDate,input.reason,plannedStart,plannedEnd,amountSatang,now,note,now,now),env.DB.prepare(`INSERT INTO admin_audit(id,action,entity_key,reason,before_json,after_json,created_at) VALUES(?,?,?,?,?,?,?)`).bind(crypto.randomUUID(),"OT_PREAPPROVE",otId,input.reason,null,JSON.stringify({employeeId:input.employeeId,workDate:input.workDate,fixedAmountBaht:input.fixedAmountBaht,plannedStart,plannedEnd}),now)]);await enqueueSheetSync(env,{kind:"SHEETS_SYNC",entityType:"OT_REQUEST",entityKey:otId,entityVersion:version,traceId:otId});const timeText=plannedStart||plannedEnd?`\nเวลาโดยประมาณ: ${plannedStart||"?"}–${plannedEnd||"?"} น.`:"";await pushConfirmation(env,employee.lineUserId,"ยืนยันทำ OT",`วันที่: ${input.workDate}${timeText}\nเหตุผล: ${input.reason}\nOT แบบเหมา: ${input.fixedAmountBaht} บาท\nกรุณายืนยันก่อนเริ่มงาน`,`a=ot_accept&id=${encodeURIComponent(otId)}`,`a=ot_decline&id=${encodeURIComponent(otId)}`,otId);return{otId,version};
}

export async function finalizeFixedOt(env:Env,raw:unknown):Promise<{otId:string;status:string;version:number}>{
  if(!raw||typeof raw!=="object")throw new Error("Invalid OT final payload");const body=raw as Record<string,unknown>,otId=String(body.otId||"").trim(),approved=body.approved===true,finalAmountBaht=body.finalAmountBaht==null?null:Number(body.finalAmountBaht),note=String(body.note||"").trim();if(!otId)throw new Error("otId is required");const row=await env.DB.prepare(`SELECT o.*,e.staff_name,e.line_user_id,e.scheduled_out FROM ot_requests o JOIN employees e ON e.employee_id=o.employee_id WHERE o.ot_id=? LIMIT 1`).bind(otId).first<Record<string,unknown>>();if(!row)throw new Error("OT request not found");if(approved&&String(row.employee_confirm_status)!=="ACCEPTED")throw new Error("Employee must accept OT before final approval");const daily=await env.DB.prepare(`SELECT time_out FROM attendance_daily WHERE employee_id=? AND work_date=?`).bind(row.employee_id,row.work_date).first<{time_out:string}>();if(approved&&!daily?.time_out)throw new Error("A valid Time_Out or attendance correction is required before final OT approval");const amountSatang=approved?(finalAmountBaht==null?Number(row.fixed_amount_satang):fixedOtSatang(finalAmountBaht)):0,minutes=actualOtMinutes(daily?.time_out||null,String(row.scheduled_out),row.planned_start?String(row.planned_start):null),status=approved?"APPROVED":"REJECTED",now=new Date().toISOString(),version=Number(row.version||0)+1;
  await env.DB.batch([env.DB.prepare(`UPDATE ot_requests SET owner_final_status=?,owner_final_amount_satang=?,owner_final_at=?,actual_ot_minutes=?,status=?,note=?,version=version+1,updated_at=? WHERE ot_id=?`).bind(status,amountSatang,now,minutes,status,note||String(row.note||""),now,otId),env.DB.prepare(`INSERT INTO admin_audit(id,action,entity_key,reason,before_json,after_json,created_at) VALUES(?,?,?,?,?,?,?)`).bind(crypto.randomUUID(),"OT_FINALIZE",otId,note||status,JSON.stringify({status:row.status,ownerFinalStatus:row.owner_final_status,ownerFinalAmountSatang:row.owner_final_amount_satang}),JSON.stringify({status,ownerFinalAmountSatang:amountSatang,actualOtMinutes:minutes}),now)]);await enqueueSheetSync(env,{kind:"SHEETS_SYNC",entityType:"OT_REQUEST",entityKey:otId,entityVersion:version,traceId:`ot_final_${otId}`});if(daily)await recalculateDailyPayroll(env,String(row.employee_id),String(row.work_date),{finalizeMissingPunch:false,traceId:`ot_payroll_${otId}`});await pushText(env,String(row.line_user_id),approved?`Owner ยืนยัน OT วันที่ ${String(row.work_date)} แล้ว ✅\nยอด OT ${amountSatang/100} บาท`:`OT วันที่ ${String(row.work_date)} ไม่ได้รับการอนุมัติยอดจ่าย`,otId);return{otId,status,version};
}
