import { enqueueSheetSync } from "../db/repositories";
import { getEmployeeById,resolveWageSnapshot } from "../payroll/repository";
import { getSheetValues } from "../sheets/client";
import { isIsoDate,minutesOf } from "../shared/time";
import type { Env } from "../types";

function asTime(value:unknown,fallback:string):string{const text=String(value??"").trim()||fallback;minutesOf(text);return text;}
export async function importShiftScheduleFromSheet(env:Env):Promise<{count:number}>{
  const values=await getSheetValues(env,`'${env.SHEET_SHIFT_SCHEDULE}'!A1:Z1000`);if(!values.length)throw new Error(`Sheet ${env.SHEET_SHIFT_SCHEDULE} is empty`);
  const headers=(values[0]||[]).map(v=>String(v??"").trim()),index=new Map(headers.map((h,i)=>[h,i]));for(const name of["Work_Date","Employee_ID","Status"])if(!index.has(name))throw new Error(`Missing shift column: ${name}`);const at=(row:unknown[],name:string)=>row[index.get(name)!];
  const statements:D1PreparedStatement[]=[],jobs:Array<{entityKey:string;version:number}>=[],now=new Date().toISOString();
  for(const row of values.slice(1)){const employeeId=String(at(row,"Employee_ID")??"").trim();if(!employeeId)continue;const workDate=String(at(row,"Work_Date")??"").trim(),statusRaw=String(at(row,"Status")??"").trim().toUpperCase(),status=statusRaw==="DAY_OFF"?"DAY_OFF":statusRaw==="CANCELLED"?"CANCELLED":"EXPECTED";if(!isIsoDate(workDate))throw new Error(`Invalid Work_Date for ${employeeId}`);const employee=await getEmployeeById(env,employeeId);if(!employee)throw new Error(`Employee not found: ${employeeId}`);const scheduledIn=asTime(index.has("Scheduled_In")?at(row,"Scheduled_In"):undefined,employee.scheduledIn),scheduledOut=asTime(index.has("Scheduled_Out")?at(row,"Scheduled_Out"):undefined,employee.scheduledOut);if(minutesOf(scheduledOut)<=minutesOf(scheduledIn))throw new Error(`Scheduled_Out must be later than Scheduled_In for ${employeeId}`);const wage=await resolveWageSnapshot(env,employee,workDate),note=index.has("Note")?String(at(row,"Note")??"").trim():"";const existing=await env.DB.prepare(`SELECT version FROM employee_shift_days WHERE employee_id=? AND work_date=?`).bind(employeeId,workDate).first<{version:number}>(),version=Number(existing?.version||0)+1;statements.push(env.DB.prepare(`INSERT INTO employee_shift_days(employee_id,work_date,scheduled_in,scheduled_out,daily_wage_snapshot_satang,wage_source_id,status,note,version,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(employee_id,work_date) DO UPDATE SET scheduled_in=excluded.scheduled_in,scheduled_out=excluded.scheduled_out,daily_wage_snapshot_satang=excluded.daily_wage_snapshot_satang,wage_source_id=excluded.wage_source_id,status=excluded.status,note=excluded.note,version=employee_shift_days.version+1,updated_at=excluded.updated_at`).bind(employeeId,workDate,scheduledIn,scheduledOut,wage.dailyWageSatang,wage.wageSourceId,status,note,version,now,now));jobs.push({entityKey:`${employeeId}|${workDate}`,version});}
  if(statements.length)await env.DB.batch(statements);for(const job of jobs)await enqueueSheetSync(env,{kind:"SHEETS_SYNC",entityType:"SHIFT_SCHEDULE",entityKey:job.entityKey,entityVersion:job.version,traceId:`shift_import_${crypto.randomUUID()}`});return{count:statements.length};
}
