import { enqueueSheetSync } from "../db/repositories";
import { getSheetValues } from "../sheets/client";
import { addDays,isIsoDate,isoDateInBangkok } from "../shared/time";
import type { EmployeeImportInput,Env } from "../types";

const required=["Employee_ID","Staff_Name","LINE_User_ID","Scheduled_In","Scheduled_Out","Status","Daily_Wage","Grace_Min"];
function asTime(value:unknown):string{
  if(typeof value==="number"&&value>=0&&value<1){const minutes=Math.round(value*1440)%1440;return`${String(Math.floor(minutes/60)).padStart(2,"0")}:${String(minutes%60).padStart(2,"0")}`;}
  const text=String(value??"").trim();if(/^\d{1,2}:\d{2}$/.test(text)){const[h,m]=text.split(":").map(Number);if(h!<24&&m!<60)return`${String(h).padStart(2,"0")}:${String(m).padStart(2,"0")}`;}throw new Error(`Invalid time: ${text}`);
}
function finite(value:unknown,name:string):number{const n=Number(value);if(!Number.isFinite(n)||n<0)throw new Error(`Invalid ${name}`);return n;}
function optionalBoolean(value:unknown,name:string,strict=true):boolean|undefined{
  if(value==null||String(value).trim()==="")return undefined;const normalized=String(value).trim().toLowerCase();
  if(value===true||value===1||["true","1","yes","y","ใช่"].includes(normalized))return true;
  if(value===false||value===0||["false","0","no","n","ไม่"].includes(normalized))return false;
  if(strict)throw new Error(`Invalid ${name}`);return undefined;
}
function optionalDate(value:unknown,name:string):string|undefined{const text=String(value??"").trim();if(!text)return undefined;if(!isIsoDate(text))throw new Error(`Invalid ${name}; expected YYYY-MM-DD`);return text;}
export async function importEmployeesFromConfiguredSheet(env:Env):Promise<{count:number;employees:Array<{employeeId:string;staffName:string;lineUserId:string}>}>{
  const values=await getSheetValues(env,`'${env.SHEET_STAFF_CONFIG}'!A1:Z500`);if(!values.length)throw new Error(`Sheet ${env.SHEET_STAFF_CONFIG} is empty`);
  const inputs=parseStaffRows(values);
  await importEmployees(env,inputs);return{count:inputs.length,employees:inputs.map(({employeeId,staffName,lineUserId})=>({employeeId,staffName,lineUserId}))};
}
export function parseStaffRows(values:unknown[][]):EmployeeImportInput[]{
  const headers=(values[0]||[]).map(v=>String(v??"").trim()),index=new Map(headers.map((h,i)=>[h,i]));for(const name of required)if(!index.has(name))throw new Error(`Missing staff column: ${name}`);
  const at=(row:unknown[],name:string)=>row[index.get(name)!];
  return values.slice(1).filter(row=>String(at(row,"Employee_ID")??"").trim()).map(row=>{
    const canSubmitExpense=index.has("Can_Submit_Expense")?optionalBoolean(at(row,"Can_Submit_Expense"),"Can_Submit_Expense"):undefined;
    const wageEffectiveFrom=index.has("Wage_Effective_From")?optionalDate(at(row,"Wage_Effective_From"),"Wage_Effective_From"):undefined;
    return{employeeId:String(at(row,"Employee_ID")).trim(),staffName:String(at(row,"Staff_Name")).trim(),lineUserId:String(at(row,"LINE_User_ID")).trim(),scheduledIn:asTime(at(row,"Scheduled_In")),scheduledOut:asTime(at(row,"Scheduled_Out")),status:String(at(row,"Status")).toLowerCase()==="active"?"ACTIVE":"INACTIVE",dailyWageBaht:finite(at(row,"Daily_Wage"),"Daily_Wage"),...(wageEffectiveFrom===undefined?{}:{wageEffectiveFrom}),graceMin:finite(at(row,"Grace_Min"),"Grace_Min"),lateDeductionBaht:optionalBoolean(index.has("Deduct_Late")?at(row,"Deduct_Late"):undefined,"Deduct_Late",false)===false?0:index.has("Late_Deduction_Baht")?finite(at(row,"Late_Deduction_Baht")||0,"Late_Deduction_Baht"):0,earlyDeductionBaht:optionalBoolean(index.has("Deduct_Early")?at(row,"Deduct_Early"):undefined,"Deduct_Early",false)===false?0:index.has("Early_Deduction_Baht")?finite(at(row,"Early_Deduction_Baht")||0,"Early_Deduction_Baht"):0,...(canSubmitExpense===undefined?{}:{canSubmitExpense})};
  });
}
export async function importEmployees(env:Env,inputs:EmployeeImportInput[]):Promise<void>{
  if(!Array.isArray(inputs)||inputs.length<1||inputs.length>200)throw new Error("employees must contain 1-200 rows");const ids=new Set<string>(),lines=new Set<string>(),today=isoDateInBangkok();
  for(const e of inputs){if(!/^[A-Za-z0-9_-]{1,40}$/.test(e.employeeId)||!e.staffName.trim()||!/^U[a-fA-F0-9]{20,64}$/.test(e.lineUserId)||!/^\d{2}:\d{2}$/.test(e.scheduledIn)||!/^\d{2}:\d{2}$/.test(e.scheduledOut)||!Number.isFinite(e.dailyWageBaht)||e.dailyWageBaht<0||!Number.isFinite(e.graceMin)||e.graceMin<0||!Number.isFinite(e.lateDeductionBaht)||e.lateDeductionBaht<0||(e.earlyDeductionBaht!==undefined&&(!Number.isFinite(e.earlyDeductionBaht)||e.earlyDeductionBaht<0))||(e.wageEffectiveFrom!==undefined&&!isIsoDate(e.wageEffectiveFrom)))throw new Error(`Invalid employee: ${e.employeeId||"unknown"}`);if(ids.has(e.employeeId)||lines.has(e.lineUserId))throw new Error(`Duplicate employee or LINE ID: ${e.employeeId}`);ids.add(e.employeeId);lines.add(e.lineUserId);}
  for(const e of inputs){const current=await env.DB.prepare(`SELECT daily_wage_satang FROM employees WHERE employee_id=?`).bind(e.employeeId).first<{daily_wage_satang:number}>();if(current&&Number(current.daily_wage_satang)!==Math.round(e.dailyWageBaht*100)&&!e.wageEffectiveFrom)throw new Error(`Wage_Effective_From is required when Daily_Wage changes for ${e.employeeId}`);if(!current&&e.wageEffectiveFrom&&e.wageEffectiveFrom>today)throw new Error(`A new employee cannot start with a future-only wage: ${e.employeeId}`);}
  const now=new Date().toISOString(),release=inputs.map(e=>env.DB.prepare(`UPDATE employees SET line_user_id=? WHERE employee_id=?`).bind(`IMPORT_${e.employeeId}_${crypto.randomUUID()}`,e.employeeId)),upserts=inputs.map(e=>env.DB.prepare(`INSERT INTO employees(employee_id,staff_name,line_user_id,scheduled_in,scheduled_out,daily_wage_satang,grace_min,late_deduction_satang,early_deduction_satang,can_submit_expense,status,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(employee_id) DO UPDATE SET staff_name=excluded.staff_name,line_user_id=excluded.line_user_id,scheduled_in=excluded.scheduled_in,scheduled_out=excluded.scheduled_out,daily_wage_satang=excluded.daily_wage_satang,grace_min=excluded.grace_min,late_deduction_satang=excluded.late_deduction_satang,early_deduction_satang=excluded.early_deduction_satang${e.canSubmitExpense===undefined?"":",can_submit_expense=excluded.can_submit_expense"},status=excluded.status,updated_at=excluded.updated_at`).bind(e.employeeId,e.staffName.trim(),e.lineUserId,e.scheduledIn,e.scheduledOut,Math.round(e.dailyWageBaht*100),Math.round(e.graceMin),Math.round(e.lateDeductionBaht*100),Math.round((e.earlyDeductionBaht||0)*100),e.canSubmitExpense?1:0,e.status,now));
  const wageStatements:D1PreparedStatement[]=[];
  for(const e of inputs){const amount=Math.round(e.dailyWageBaht*100);if(e.wageEffectiveFrom){const next=await env.DB.prepare(`SELECT effective_from FROM employee_wage_history WHERE employee_id=? AND effective_from>? ORDER BY effective_from LIMIT 1`).bind(e.employeeId,e.wageEffectiveFrom).first<{effective_from:string}>(),effectiveTo=next?.effective_from?addDays(next.effective_from,-1):null,wageId=`wage_${e.employeeId}_${e.wageEffectiveFrom.replaceAll("-","")}`;wageStatements.push(env.DB.prepare(`UPDATE employee_wage_history SET effective_to=?,updated_at=?,version=version+1 WHERE employee_id=? AND effective_from<? AND (effective_to IS NULL OR effective_to>=?)`).bind(addDays(e.wageEffectiveFrom,-1),now,e.employeeId,e.wageEffectiveFrom,e.wageEffectiveFrom));wageStatements.push(env.DB.prepare(`INSERT INTO employee_wage_history(wage_id,employee_id,daily_wage_satang,effective_from,effective_to,source,note,version,created_at,updated_at) VALUES(?,?,?,?,?,'STAFF_CONFIG','Imported with explicit effective date',1,?,?) ON CONFLICT(employee_id,effective_from) DO UPDATE SET daily_wage_satang=excluded.daily_wage_satang,effective_to=excluded.effective_to,source=excluded.source,note=excluded.note,version=employee_wage_history.version+1,updated_at=excluded.updated_at`).bind(wageId,e.employeeId,amount,e.wageEffectiveFrom,effectiveTo,now,now));}else{wageStatements.push(env.DB.prepare(`INSERT OR IGNORE INTO employee_wage_history(wage_id,employee_id,daily_wage_satang,effective_from,effective_to,source,note,version,created_at,updated_at) VALUES(?,?,?,'1970-01-01',NULL,'IMPORT_BASELINE','Initial imported wage',1,?,?)`).bind(`wage_${e.employeeId}_baseline`,e.employeeId,amount,now,now));}}
  const refreshCurrentWages=inputs.map(e=>env.DB.prepare(`UPDATE employees SET daily_wage_satang=COALESCE((SELECT daily_wage_satang FROM employee_wage_history WHERE employee_id=? AND effective_from<=? AND (effective_to IS NULL OR effective_to>=?) ORDER BY effective_from DESC LIMIT 1),daily_wage_satang),updated_at=? WHERE employee_id=?`).bind(e.employeeId,today,today,now,e.employeeId));
  await env.DB.batch([...release,...upserts,...wageStatements,...refreshCurrentWages]);const traceId=`staff_wages_${crypto.randomUUID()}`;
  for(const e of inputs){const rows=await env.DB.prepare(`SELECT wage_id,version FROM employee_wage_history WHERE employee_id=? ORDER BY effective_from`).bind(e.employeeId).all<{wage_id:string;version:number}>();for(const row of rows.results||[])await enqueueSheetSync(env,{kind:"SHEETS_SYNC",entityType:"WAGE_HISTORY",entityKey:String(row.wage_id),entityVersion:Number(row.version),traceId});}
}
