import { calculatePayroll } from "../domain/payroll";
import { randomId } from "../shared/ids";
import { addDays,weekStartMonday } from "../shared/time";
import type { AttendanceCommitRequest,AttendanceCommitResult,Env } from "../types";
interface State{timeIn:string|null;timeOut:string|null;review:boolean;version:number}
export class AttendanceCoordinator{
  constructor(private readonly state:DurableObjectState,private readonly env:Env){}
  async fetch(request:Request):Promise<Response>{
    if(request.method!=="POST")return new Response("Method not allowed",{status:405});
    if(new URL(request.url).pathname==="/sync"){const next=await request.json() as State;await this.state.storage.transaction(async tx=>{await tx.put("state",next);});return Response.json({ok:true});}
    const input=await request.json() as AttendanceCommitRequest;return Response.json(await this.state.blockConcurrencyWhile(async()=>this.commit(input)));
  }
  private async commit(input:AttendanceCommitRequest):Promise<AttendanceCommitResult>{
    const existing=await this.env.DB.prepare(`SELECT a.event_id,a.work_date,a.official_time,a.version,d.late_minutes,d.confirmed_wage_satang,d.pending_wage_satang FROM attendance_events a LEFT JOIN attendance_daily d ON d.employee_id=a.employee_id AND d.work_date=a.work_date WHERE a.message_id=? LIMIT 1`).bind(input.messageId).first<Record<string,unknown>>();
    if(existing)return{eventId:String(existing.event_id),punchType:"DUPLICATE",workDate:String(existing.work_date),officialTime:String(existing.official_time||""),status:"DUPLICATE",lateMinutes:Number(existing.late_minutes||0),confirmedWageSatang:Number(existing.confirmed_wage_satang||0),pendingWageSatang:Number(existing.pending_wage_satang||0),validationCode:"DUPLICATE_MESSAGE",version:Number(existing.version||0)};
    const key="state";let current=await this.state.storage.transaction(tx=>tx.get<State>(key));
    if(!current){const row=await this.env.DB.prepare(`SELECT time_in,time_out,review_flag,version FROM attendance_daily WHERE employee_id=? AND work_date=?`).bind(input.employee.employeeId,input.workDate).first<Record<string,unknown>>();current={timeIn:row?.time_in?String(row.time_in):null,timeOut:row?.time_out?String(row.time_out):null,review:Number(row?.review_flag||0)===1,version:Number(row?.version||0)};}
    if(current.timeIn&&current.timeOut)return{eventId:"",punchType:"COMPLETE",workDate:input.workDate,officialTime:input.officialTime,status:"ALREADY_COMPLETE",lateMinutes:0,confirmedWageSatang:0,pendingWageSatang:0,validationCode:"DAY_ALREADY_COMPLETE",version:current.version};
    const punch=current.timeIn?"OUT":"IN";if(punch==="IN")current.timeIn=input.officialTime;else current.timeOut=input.officialTime;
    current.review=current.review||input.validationReview||input.reading.needsNewPhoto;const nextVersion=current.version+1,payroll=calculatePayroll({employee:input.employee,timeIn:current.timeIn,timeOut:current.timeOut,review:current.review});
    const eventId=randomId("att"),weekStart=weekStartMonday(input.workDate),paySunday=addDays(weekStart,6),now=new Date().toISOString(),note=input.validationNote;
    await this.env.DB.batch([
      this.env.DB.prepare(`INSERT INTO attendance_events(event_id,webhook_event_id,message_id,employee_id,work_date,punch_type,official_time,status,confidence,line_time,line_diff_minutes,image_key,note,validation_code,trace_id,created_at,version) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(eventId,input.webhookEventId,input.messageId,input.employee.employeeId,input.workDate,punch,input.officialTime,current.review?"REVIEW":"NORMAL",input.reading.confidence,input.lineTime,input.lineDiffMinutes,input.imageKey,note,input.validationCode,input.traceId,now,nextVersion),
      this.env.DB.prepare(`INSERT INTO attendance_daily(employee_id,work_date,scheduled_in,scheduled_out,grace_min,late_deduction_satang,early_deduction_satang,time_in,time_out,work_minutes,late_minutes,early_out_minutes,daily_wage_satang,confirmed_wage_satang,pending_wage_satang,pay_status,review_flag,version,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(employee_id,work_date) DO UPDATE SET time_in=excluded.time_in,time_out=excluded.time_out,work_minutes=excluded.work_minutes,late_minutes=excluded.late_minutes,early_out_minutes=excluded.early_out_minutes,confirmed_wage_satang=excluded.confirmed_wage_satang,pending_wage_satang=excluded.pending_wage_satang,pay_status=excluded.pay_status,review_flag=excluded.review_flag,version=excluded.version,updated_at=excluded.updated_at`).bind(input.employee.employeeId,input.workDate,input.employee.scheduledIn,input.employee.scheduledOut,input.employee.graceMin,input.employee.lateDeductionSatang,input.employee.earlyDeductionSatang,current.timeIn,current.timeOut,payroll.workMinutes,payroll.lateMinutes,payroll.earlyOutMinutes,input.employee.dailyWageSatang,payroll.confirmedWageSatang,payroll.pendingWageSatang,payroll.payStatus,current.review?1:0,nextVersion,now),
      this.env.DB.prepare(`INSERT INTO payroll_weekly(employee_id,week_start,pay_sunday,work_days,confirmed_amount_satang,pending_amount_satang,status,version,updated_at) SELECT ?,?,?,COALESCE(SUM(CASE WHEN time_in IS NOT NULL AND time_out IS NOT NULL THEN 1 ELSE 0 END),0),COALESCE(SUM(confirmed_wage_satang),0),COALESCE(SUM(pending_wage_satang),0),CASE WHEN COALESCE(SUM(pending_wage_satang),0)>0 THEN 'REVIEW' WHEN COALESCE(SUM(confirmed_wage_satang),0)>0 THEN 'READY' ELSE 'NO_AMOUNT' END,?,? FROM attendance_daily WHERE employee_id=? AND work_date BETWEEN ? AND ? ON CONFLICT(employee_id,week_start) DO UPDATE SET work_days=excluded.work_days,confirmed_amount_satang=excluded.confirmed_amount_satang,pending_amount_satang=excluded.pending_amount_satang,status=excluded.status,version=payroll_weekly.version+1,updated_at=excluded.updated_at`).bind(input.employee.employeeId,weekStart,paySunday,nextVersion,now,input.employee.employeeId,weekStart,paySunday)
    ]);
    current.version=nextVersion;await this.state.storage.transaction(async tx=>{await tx.put(key,current!);});
    return{eventId,punchType:punch,workDate:input.workDate,officialTime:input.officialTime,status:current.review?"REVIEW":"NORMAL",lateMinutes:payroll.lateMinutes,confirmedWageSatang:payroll.confirmedWageSatang,pendingWageSatang:payroll.pendingWageSatang,validationCode:input.validationCode,version:nextVersion};
  }
}
